--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      unam.fi
-- Project :      modelo-global.DM1
-- Author :       rho
--
-- Date Created : Sunday, January 17, 2021 23:03:23
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: AUTO_F3_EFM_S2 
--

CREATE TABLE AUTO_F3_EFM_S2(
    AUTO_ID    NUMBER(10, 0)    NOT NULL,
    FOTO       BLOB             NOT NULL,
    CONSTRAINT AUTO_PK PRIMARY KEY (AUTO_ID)
)
;



-- 
-- TABLE: CLIENTE_F3_EFM_S2 
--

CREATE TABLE CLIENTE_F3_EFM_S2(
    CLIENTE_ID            NUMBER(10, 0)    NOT NULL,
    NOMBRE                VARCHAR2(40)     NOT NULL,
    AP_PATERNO            VARCHAR2(40)     NOT NULL,
    AP_MATERNO            VARCHAR2(40)     NOT NULL,
    NUM_IDENTIFICACION    VARCHAR2(18)     NOT NULL,
    EMAIL                 VARCHAR2(500)    NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: STATUS_AUTO 
--

CREATE TABLE STATUS_AUTO(
    STATUS_AUTO_ID    NUMBER(2, 0)    NOT NULL,
    CLAVE             VARCHAR2(20)    NOT NULL,
    DESCRIPCION       VARCHAR2(40)    NOT NULL,
    CONSTRAINT STATUS_AUTO_PK PRIMARY KEY (STATUS_AUTO_ID)
)
;



-- 
-- TABLE: historico_status_auto_F2_EFM_S2 
--

CREATE TABLE historico_status_auto_F2_EFM_S2(
    HISTORICO_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS           DATE             NOT NULL,
    AUTO_ID                NUMBER(10, 0)    NOT NULL,
    STATUS_AUTO_ID         NUMBER(2, 0)     NOT NULL,
    CONSTRAINT HISTORICO_STATUS_AUTO_PK PRIMARY KEY (HISTORICO_STATUS_ID), 
    CONSTRAINT HIST_STAUTO_F2_AUTO_ID_FK FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO_F3_EFM_S2(AUTO_ID),
    CONSTRAINT HIST_STAUTO_F2_STAUTO_ID_FK FOREIGN KEY (STATUS_AUTO_ID)
    REFERENCES STATUS_AUTO(STATUS_AUTO_ID)
)
;



-- 
-- TABLE: MARCA_R_EFM_S2 
--

CREATE TABLE MARCA_R_EFM_S2(
    MARCA_ID       NUMBER(3, 0)     NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    CONSTRAINT MARCA_PK PRIMARY KEY (MARCA_ID)
)
;



-- 
-- TABLE: MODELO_R_EFM_S2 
--

CREATE TABLE MODELO_R_EFM_S2(
    MODELO_ID      NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    MARCA_ID       NUMBER(3, 0)     NOT NULL,
    CONSTRAINT MODELO_PK PRIMARY KEY (MODELO_ID), 
    CONSTRAINT MODELO_R_MARCA_ID_FK FOREIGN KEY (MARCA_ID)
    REFERENCES MARCA_R_EFM_S2(MARCA_ID)
)
;



